# Setup
title:        Arslan Chaudhry
tagline:      Machine Learning/ AI Researcher & Rhodes Scholar, University of Oxford
email:        arslan dot ch at deepmind dot com
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Arslan Chaudhry
  url:        https://arslan-chaudhry.github.io/

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown
