# Setup
title:        Arslan Chaudhry
tagline:      University of Oxford DPhil Student in Machine Learning and Computer Vision
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Arslan Chaudhry
  url:        https://arslan-chaudhry.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
