# Setup
title:        Arslan Chaudhry
tagline:      Machine Learning/ AI Researcher & Rhodes Scholar, University of Oxford
email:        arslan dot chaudhry at eng dot ox dot ac dot uk
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Arslan Chaudhry
  url:        https://arslan-chaudhry.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
