# Setup
title:        Arslan Chaudhry
tagline:      DPhil Student & Rhodes Scholar, University of Oxford
email:        arslan.chaudhry at eng.ox.ac.uk
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Arslan Chaudhry
  url:        https://arslan-chaudhry.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
